### ISSUE TITLE
How to get T_add from mixbench?

### ISSUE THREAD

**Issue by chunhualiao** [ekondis/mixbench#12]
Hi, 

I am very interested in reproducing the model you described in "A quantitative roofline model for GPU kernel performance estimation using micro-benchmarks and hardware metric profiling, 2017, J. Parallel Distributed computing."  In the paper, it reads : The TSP , TDP , Tint , Tadd metrics were collected by using a microbenchmark that excessively performs execution of independent arithmetic instructions.  

My understanding is that the microbenchmark mentioned in the paper is mixbench.  I am able to obtain Tsp, Tdp, and Tint. It works very well. However, I cannot find Tadd in the results.  Did I miss anything?  

Thanks!

**Comment by ekondis** [comment]
This is a plausible thought but actually simpler benchmarks were used for the estimation of the parameters you referred to. These benchmarks haven't been published yet but this is something I intend to do in the not too distant future. For the moment you can use as Tadd the half value of Tsp. This the theoretical ratio and experiments have proven it to be correct.

**Comment by chunhualiao** [comment]
Thanks for your prompt responses.  I looked at the two numbers (T_sp vs. T_add) in your paper.  Table 7: 

![table7](https://user-images.githubusercontent.com/1627206/41688625-b815fc62-74a1-11e8-8e22-cf9fb04fd109.png)

* GTX 480:  1462.20 vs. 732.86:  satisfying T_sp/2 = T_add
* GTX 660: 1940.80 vs. 621.36  : not quite
* GTX-960: 2832.70 vs. 1426.15:  satisfying T_sp/2 = T_add
* GTX-1060: 4609.54 vs. 2304.10: satisfying T_sp/2 = T_add
* Tesla M2050: 1011.36 vs. 504.88 : satisfying T_sp/2 = T_add
* Tesla K20c: 3115.24 vs 969.28:   not quite

Anyway, I will follow your suggestions for now.

**Comment by ekondis** [comment]
**Updated**: You're right but this is still mostly on par with the theoretical specifications. Both GTX660 & K20c belong to the Kepler family which offers a 1/2.45 throughput ratio on integer additions contrary to other architectures (160 integer additions per clock per SM vs 196 SP multiply-adds per clock per SM). This fact is also expressed in table 8, last column (Wother). 
For further information I would suggest direct email as this discussion is out of topic.
