### ISSUE TITLE
About mixbench

### ISSUE THREAD

**Issue by mahmoodn** [ekondis/mixbench#13]
May I know what is the purpose of readonly version?
Also, is the vector size hard coded for GTX 480 only?

**Comment by ekondis** [comment]
The "ro" follows a different approach from the "alt" variation. The 1st essentially performs read-only memory accesses whereas the 2nd involves both reads and writes. The general idea is the same in both cases but some GPUs might flavor the 1st or the 2nd and that also varies as it depends on the operational intensity.

Yes, for the CUDA implementation the elements are scalars.

**Comment by mahmoodn** [comment]
Thanks. The vector size in ro and alt are also different.
So, comparing read-only vs. read/write on different input sizes may bias the performance result. Don't you agree? I think the same vector size should be used. 

More over, I see big vector sizes, e.g. 128*1024*1024 give the same result but with slower runtime.

**Comment by ekondis** [comment]
They are different approaches. But what do you mean exactly by vector size? Are you referring to the granularity in the "read-only" code or to the kernel launch configuration?

Eventually, the metric we care about is the operational intensity. You may freely do experiments using different parameters/configurations. I'd love to hear of your results.

**Comment by mahmoodn** [comment]
I mean [this](https://github.com/ekondis/mixbench/blob/master/main-cuda.cpp#L17) part of code.
```
#ifdef READONLY
#define VECTOR_SIZE (32*1024*1024)
#else
#define VECTOR_SIZE (8*1024*1024)
#endif`
```
Why different vector sizes are used in ro and alt? Shouldn't be the same?

**Comment by ekondis** [comment]
I see. This corresponds to the memory space used which directly affects the total workload. The _read-only_ kernel is not as "heavy" as the other so a larger workload is used just to minimize launch overheads. 

Perhaps the name VECTOR_SIZE is misleading.

**Comment by mahmoodn** [comment]
Since ro and alt have some differences in results, which one is more insightful for presentation? for example, I have seen about 800 GIOPs difference between these two. I haven't seen any report that what is written as peak performance (e.g. GFLOPs) in the datasheets is corresponding to read only or read/write.
Have you seen such a thing?

**Comment by mahmoodn** [comment]
The same question may be applied to memory bandwidth. Mixbench reports `Memory bandwidth:    484.44 GB/sec` which is similar to datasheets. So, is that correspond reading and writing operations?

**Comment by ekondis** [comment]
Theoretically, there should be no difference between the performance of both programs but in practice there can always be bubtle details in the architecture or the compiler generated code that affect the actual results.

The "Memory bandwidth" is derived from the memory clocks. In theory that corresponds to the aggregated read & write bandwidth.
