### ISSUE TITLE
FLOPS is greater than theoretical

### ISSUE THREAD

**Issue by mahmoodn** [ekondis/mixbench#14]
On a 2080Ti, I see that the SP FLOPs rate is reported larger than the device information
```
Device:              GeForce RTX 2080 Ti
CUDA driver version: 10.10
GPU clock rate:      1545 MHz
Memory clock rate:   3500 MHz
Memory bus width:    352 bits
WarpSize:            32
L2 cache size:       5632 KB
Total global mem:    10989 MB
ECC enabled:         No
Compute Capability:  7.5
Total SPs:           4352 (68 MPs x 64 SPs/MP)
Compute throughput:  13447.68 GFlops (theoretical single precision FMAs)
Memory bandwidth:    616.00 GB/sec
```

The two last lines are:

```
           31,    124.000,    2.10,15876.84, 128.04,     62.000,   66.73,  498.82,   8.05,    248.000,    2.12,31399.99, 126.61,   124.000,    2.10,15866.67, 127.96
           32,        inf,    2.16,15914.12,   0.00,        inf,   68.87,  498.90,   0.00,        inf,    2.18,31532.88,   0.00,       inf,    2.31,14886.00,   0.00
```

So, the device is about 13.5 TFLOPs but the program reports 15.8 TFLOPs. Is that a sort of tolerable error?

**Comment by ekondis** [comment]
Yes, usually it is normal as it depends on the actual current GPU clock. The 13.5 TFLOPs peak is based on the 1545MHz clock rate as reported by the driver but the GPU can actually hit higher rates, at least momentarily. You can use nvidia-smi to monitor the GPU clock.

**Comment by mahmoodn** [comment]
Thanks. One more thing. What does "inf" mean then? Sort of an overflow?

**Comment by ekondis** [comment]
No, _inf_ is not an overflow. It actually means that operational intensity is infinite as no explicit memory accesses are performed.
