### ISSUE TITLE
memory ratio

### ISSUE THREAD

**Issue by mahmoodn** [ekondis/mixbench#15]
May I know the logic which use used for memory_ratio? Why that is limited to 32? What is the purpose of running with multiple memory_raio values while we know the ratio of 32 yields almost nothing?
Also, why more than 32 is considered as error?
Which document did you use to include memory_ratio?

**Comment by ekondis** [comment]
The design of _alt_ variation utilizes an inner loop of a fixed number of 32 operations which are split to compute and memory operations. The memory_ratio argument specifies how many operations of the 32 in total will be memory related and the rest of them will be compute related.

**Comment by mahmoodn** [comment]
So is that 32 the same as warp size?

**Comment by ekondis** [comment]
Yes, but this is a coincidence.
