### ISSUE TITLE
Allow building of program taking parameters to specify what to build

### ISSUE THREAD

**Issue by yxliang01** [ekondis/mixbench#16]
When building the opencl version, it is possible to have multiple OpenCL installations in the same system. Better to take in parameters to allow users to select which to build with. Maybe having a meta-make system is beneficial for this mixbench system (e.g. cmake) since there are lots of components (e.g. OpenCL, CUDA, HIP) that it is seldom that a user wants to build all of them and have the environment to build them all. Current approach requires direct modification of the makefile which is error-prone and not user-friendly.

**Comment by ekondis** [comment]
What exactly do you mean by "multiple OpenCL" installations? Multiple places with the OpenCL headers & libraries? Or multi vendor OpenCL devices?
If you want to just build the OpenCL binaries just give "make mixbench-ocl-alt mixbench-ocl-ro".
A CMakeLists would probably be preferred but required some work to do.

**Comment by yxliang01** [comment]
I meant multiple OpenCL libraries & headers from multiple vendors (e.g. Nvidia, AMD, Intel).

**Comment by ekondis** [comment]
Okay, but if you use, let's say for example, the NVidia libraries & headers then the produced executable will work for any OpenCL platform. This is what I've experienced.

**Comment by yxliang01** [comment]
According to my past experience, at least the Intel FPGA OpenCL libraries can't be used with Nvidia GPU though.

**Comment by ekondis** [comment]
Actually, I wasn't aware of this fact. I have not installed Intel FPGA environment so far. Anyway, that's why I've included some vars on the top of Makefile. I understand that this is not perfect, though.

**Comment by yxliang01** [comment]
Right. I actually just would like to give the feedback from our experience when using this tool as a potential improvement. If you think this is a good idea, maybe this can be a TODO. Otherwise, this can be closed as we have already got through our difficulties.

**Comment by ekondis** [comment]
Replacing _Make_ with _CMake_ is certainly a TODO task.

**Comment by ekondis** [comment]
Building is now CMake based.
