### ISSUE TITLE
Get lower flops when benchmarking with A100

### ISSUE THREAD

**Issue by guoshzhao** [ekondis/mixbench#18]
We are run mixbench with nvidia A100, and get lower Flops than the theory value from Nvidia. We wonder if mixbench itself has bottleneck for high performance device like A100? 

The peak flops of A100 is 19.5 TFlops with single-precision and 9.7 TFlops with double-precision. While mixbench got 13~14 TFlops with single-precision and 7 TFlops with double-precision. Looking forward to any help. Thanks in advance.

mixbench/alternating (v0.03-4-g4c6d108)
Device:              A100-SXM4-40GB
CUDA driver version: 11.0
GPU clock rate:      1410 MHz
Memory clock rate:   607 MHz
Memory bus width:    5120 bits
WarpSize:            32
L2 cache size:       40960 KB
Total global mem:    39539 MB
ECC enabled:         Yes
Compute Capability:  8.0
Total SPs:           13824 (108 MPs x 128 SPs/MP)
Compute throughput:  38983.68 GFlops (theoretical single precision FMAs)
Memory bandwidth:    1555.20 GB/sec

Total GPU memory 41459908608, free 41021603840
Buffer size:          64MB
Trade-off type:       compute with global memory (block strided)
Elements per thread:  8
Thread fusion degree: 4

Experiment ID, Single Precision ops,,,,              Double precision ops,,,,              Half precision ops,,,,                Integer operations,,,
Compute iters, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Iops/byte, ex.time,   GIOPS, GB/sec
            0,      0.250,    0.04,  218.09, 872.36,      0.125,    0.06,  150.31,1202.50,      0.500,    0.03,  537.73,1075.46,     0.250,    0.03,  285.87,1143.49
            1,      0.750,    0.03,  918.73,1224.97,      0.375,    0.05,  528.87,1410.32,      1.500,    0.03, 1650.43,1100.29,     0.750,    0.03,  873.81,1165.08
            2,      1.250,    0.03, 1571.61,1257.29,      0.625,    0.05,  885.62,1416.99,      2.500,    0.03, 2753.61,1101.45,     1.250,    0.03, 1479.37,1183.49
            3,      1.750,    0.03, 2205.54,1260.31,      0.875,    0.05, 1196.22,1367.11,      3.500,    0.03, 3703.35,1058.10,     1.750,    0.03, 2064.13,1179.50
            4,      2.250,    0.03, 2822.12,1254.28,      1.125,    0.05, 1543.03,1371.58,      4.500,    0.03, 4690.45,1042.32,     2.250,    0.03, 2681.02,1191.56
            5,      2.750,    0.03, 3428.76,1246.82,      1.375,    0.05, 1850.82,1346.05,      5.500,    0.03, 5976.34,1086.61,     2.750,    0.03, 3165.30,1151.02
            6,      3.250,    0.03, 3863.80,1188.86,      1.625,    0.05, 2188.74,1346.92,      6.500,    0.03, 6715.02,1033.08,     3.250,    0.03, 3876.99,1192.92
            7,      3.750,    0.03, 4316.31,1151.02,      1.875,    0.05, 2581.85,1376.99,      7.500,    0.03, 7809.65,1041.29,     3.750,    0.03, 4012.41,1069.98
            8,      4.250,    0.03, 5018.52,1180.83,      2.125,    0.05, 2845.75,1339.18,      8.500,    0.03, 9094.79,1069.98,     4.250,    0.05, 2774.87, 652.91
            9,      4.750,    0.03, 6133.91,1291.35,      2.375,    0.05, 3259.64,1372.48,      9.500,    0.03, 9775.73,1029.02,     4.750,    0.03, 5259.49,1107.26
           10,      5.250,    0.03, 6103.13,1162.50,      2.625,    0.05, 3379.39,1287.39,     10.500,    0.03,10720.59,1021.01,     5.250,    0.03, 5628.86,1072.16
           11,      5.750,    0.03, 6353.33,1104.93,      2.875,    0.05, 3721.80,1294.54,     11.500,    0.03,11517.31,1001.51,     5.750,    0.03, 6096.37,1060.24
           12,      6.250,    0.03, 7162.40,1145.98,      3.125,    0.05, 3959.88,1267.16,     12.500,    0.03,12800.00,1024.00,     6.250,    0.05, 4000.98, 640.16
           13,      6.750,    0.03, 7925.97,1174.22,      3.375,    0.05, 4355.62,1290.56,     13.500,    0.03,13624.42,1009.22,     6.750,    0.03, 7084.97,1049.63
           14,      7.250,    0.03, 7702.31,1062.39,      3.625,    0.05, 4495.67,1240.18,     14.500,    0.03,15174.00,1046.48,     7.250,    0.03, 7253.99,1000.55
           15,      7.750,    0.03, 7990.62,1031.05,      3.875,    0.06, 4534.86,1170.29,     15.500,    0.03,15376.47, 992.03,     7.750,    0.03, 7552.48, 974.51
           16,      8.250,    0.03, 8318.03,1008.25,      4.125,    0.06, 4934.83,1196.32,     16.500,    0.03,16461.95, 997.69,     8.250,    0.05, 5038.29, 610.70
           17,      8.750,    0.03, 8933.83,1021.01,      4.375,    0.05, 5362.38,1225.69,     17.500,    0.03,16912.52, 966.43,     8.750,    0.04, 8265.80, 944.66
           18,      9.250,    0.03, 9056.33, 979.06,      4.625,    0.06, 5436.84,1175.53,     18.500,    0.03,18888.66,1021.01,     9.250,    0.04, 8493.28, 918.19
           20,     10.250,    0.04, 9436.26, 920.61,      5.125,    0.06, 5592.04,1091.13,     20.500,    0.03,20033.37, 977.24,    10.250,    0.06, 6051.75, 590.41
           22,     11.250,    0.04, 9637.65, 856.68,      5.625,    0.07, 5723.67,1017.54,     22.500,    0.03,21784.82, 968.21,    11.250,    0.04, 9567.30, 850.43
           24,     12.250,    0.04,10035.20, 819.20,      6.125,    0.07, 5830.71, 951.95,     24.500,    0.03,23699.37, 967.32,    12.250,    0.06, 6898.53, 563.15
           28,     14.250,    0.05,10559.86, 741.04,      7.125,    0.08, 5976.88, 838.86,     28.500,    0.03,27568.65, 967.32,    14.250,    0.06, 7415.49, 520.39
           32,     16.250,    0.05,10901.70, 670.87,      8.125,    0.09, 6096.37, 750.32,     32.500,    0.04,29152.03, 896.99,    16.250,    0.07, 7940.06, 488.62
           40,     20.250,    0.06,11471.46, 566.49,     10.125,    0.11, 6334.63, 625.64,     40.500,    0.04,33677.50, 831.54,    20.250,    0.08, 8586.20, 424.01
           48,     24.250,    0.07,11988.67, 494.38,     12.125,    0.13, 6442.35, 531.33,     48.500,    0.04,36560.70, 753.83,    24.250,    0.09, 9246.53, 381.30
           56,     28.250,    0.08,12322.08, 436.18,     14.125,    0.14, 6562.31, 464.59,     56.500,    0.05,37615.58, 665.76,    28.250,    0.10, 9611.38, 340.23
           64,     32.250,    0.09,12473.84, 386.79,     16.125,    0.16, 6645.03, 412.10,     64.500,    0.05,40693.83, 630.91,    32.250,    0.11, 9890.78, 306.69
           80,     40.250,    0.11,12828.32, 318.72,     20.125,    0.20, 6734.51, 334.63,     80.500,    0.06,42016.11, 521.94,    40.250,    0.13,10271.40, 255.19
           96,     48.250,    0.12,12996.09, 269.35,     24.125,    0.24, 6774.74, 280.82,     96.500,    0.07,44322.20, 459.30,    48.250,    0.15,10569.00, 219.05
          128,     64.250,    0.16,13267.23, 206.49,     32.125,    0.31, 6890.76, 214.50,    128.500,    0.09,45971.35, 357.75,    64.250,    0.20,10979.63, 170.89
          192,     96.250,    0.24,13642.26, 141.74,     48.125,    0.46, 7000.45, 145.46,    192.500,    0.13,49340.23, 256.31,    96.250,    0.28,11355.25, 117.98
          256,    128.250,    0.32,13342.58, 104.04,     64.125,    0.62, 6905.97, 107.70,    256.500,    0.22,39616.99, 154.45,   128.250,    0.37,11573.14,  90.24

mixbench/read-only (v0.03-4-g4c6d108)
Device:              A100-SXM4-40GB
CUDA driver version: 11.0
GPU clock rate:      1410 MHz
Memory clock rate:   607 MHz
Memory bus width:    5120 bits
WarpSize:            32
L2 cache size:       40960 KB
Total global mem:    39539 MB
ECC enabled:         Yes
Compute Capability:  8.0
Total SPs:           13824 (108 MPs x 128 SPs/MP)
Compute throughput:  38983.68 GFlops (theoretical single precision FMAs)
Memory bandwidth:    1555.20 GB/sec

Total GPU memory 41459908608, free 41021603840
Buffer size:          256MB
Trade-off type:       compute with global memory (block strided)
Elements per thread:  8
Thread fusion degree: 4

Experiment ID, Single Precision ops,,,,              Double precision ops,,,,              Half precision ops,,,,                Integer operations,,,
Compute iters, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Iops/byte, ex.time,   GIOPS, GB/sec
            0,      0.250,    0.11,  299.68,1198.72,      0.125,    0.19,  179.03,1432.24,      0.500,    0.12,  575.35,1150.70,     0.250,    0.10,  327.37,1309.49
            1,      0.750,    0.10,  992.97,1323.96,      0.375,    0.19,  534.90,1426.39,      1.500,    0.10, 1999.83,1333.22,     0.750,    0.10,  992.97,1323.96
            2,      1.250,    0.10, 1696.18,1356.94,      0.625,    0.19,  895.91,1433.46,      2.500,    0.10, 3318.28,1327.31,     1.250,    0.10, 1634.82,1307.86
            3,      1.750,    0.10, 2326.48,1329.41,      0.875,    0.19, 1244.07,1421.80,      3.500,    0.10, 4546.32,1298.95,     1.750,    0.10, 2301.67,1315.24
            4,      2.250,    0.10, 2999.74,1333.22,      1.125,    0.19, 1598.44,1420.83,      4.500,    0.10, 5898.24,1310.72,     2.250,    0.10, 2970.47,1320.21
            5,      2.750,    0.10, 3664.02,1332.37,      1.375,    0.19, 1933.02,1405.83,      5.500,    0.10, 7211.21,1311.13,     2.750,    0.10, 3659.37,1330.68
            6,      3.250,    0.10, 4278.56,1316.48,      1.625,    0.19, 2282.57,1404.66,      6.500,    0.10, 8332.21,1281.88,     3.250,    0.10, 4313.76,1327.31
            7,      3.750,    0.10, 4972.70,1326.05,      1.875,    0.19, 2660.91,1419.15,      7.500,    0.10, 9818.13,1309.08,     3.750,    0.10, 4913.66,1310.31
            8,      4.250,    0.10, 5639.29,1326.89,      2.125,    0.19, 2983.40,1403.95,      8.500,    0.10,11165.54,1313.59,     4.250,    0.14, 4130.17, 971.80
            9,      4.750,    0.10, 6512.89,1371.14,      2.375,    0.19, 3360.82,1415.08,      9.500,    0.10,12471.33,1312.77,     4.750,    0.10, 6107.59,1285.81
           10,      5.250,    0.10, 6876.98,1309.90,      2.625,    0.19, 3685.37,1403.95,     10.500,    0.10,13542.49,1289.76,     5.250,    0.10, 6889.89,1312.36
           11,      5.750,    0.10, 7557.90,1314.42,      2.875,    0.19, 4022.89,1399.27,     11.500,    0.10,15026.32,1306.64,     5.750,    0.10, 7480.54,1300.96
           12,      6.250,    0.10, 8108.38,1297.34,      3.125,    0.19, 4345.17,1390.45,     12.500,    0.10,16282.24,1302.58,     6.250,    0.14, 5818.96, 931.03
           13,      6.750,    0.10, 9180.14,1360.02,      3.375,    0.19, 4677.28,1385.86,     13.500,    0.10,18189.24,1347.35,     6.750,    0.10, 8655.32,1282.27
           14,      7.250,    0.10, 9356.52,1290.56,      3.625,    0.19, 5017.11,1384.03,     14.500,    0.10,18713.05,1290.56,     7.250,    0.10, 9313.54,1284.63
           15,      7.750,    0.11, 9889.22,1276.03,      3.875,    0.19, 5346.36,1379.71,     15.500,    0.10,20476.13,1321.04,     7.750,    0.10,10004.88,1290.95
           16,      8.250,    0.11,10514.44,1274.48,      4.125,    0.20, 5641.18,1367.56,     16.500,    0.10,21479.21,1301.77,     8.250,    0.15, 7400.13, 896.99
           17,      8.750,    0.10,11650.84,1331.53,      4.375,    0.20, 6011.49,1374.06,     17.500,    0.10,23198.58,1325.63,     8.750,    0.10,11278.48,1288.97
           18,      9.250,    0.11,11543.38,1247.93,      4.625,    0.20, 6317.75,1366.00,     18.500,    0.10,24393.15,1318.55,     9.250,    0.11,11354.20,1227.48
           20,     10.250,    0.11,12002.13,1170.94,      5.125,    0.20, 6750.14,1317.10,     20.500,    0.10,26611.96,1298.14,    10.250,    0.16, 8679.91, 846.82
           22,     11.250,    0.12,12489.66,1110.19,      5.625,    0.22, 6930.95,1232.17,     22.500,    0.10,29836.18,1326.05,    11.250,    0.12,12512.84,1112.25
           24,     12.250,    0.13,12655.23,1033.08,      6.125,    0.24, 6989.56,1141.15,     24.500,    0.10,32365.50,1321.04,    12.250,    0.17, 9822.26, 801.82
           28,     14.250,    0.15,13107.20, 919.80,      7.125,    0.27, 7090.02, 995.09,     28.500,    0.10,37720.94,1323.54,    14.250,    0.18,10578.55, 742.35
           32,     16.250,    0.16,13369.45, 822.74,      8.125,    0.31, 7140.64, 878.85,     32.500,    0.10,42987.98,1322.71,    16.250,    0.20,11087.92, 682.33
           40,     20.250,    0.20,13855.57, 684.23,     10.125,    0.38, 7227.25, 713.80,     40.500,    0.11,48053.55,1186.51,    20.250,    0.23,11620.56, 573.85
           48,     24.250,    0.23,14203.59, 585.71,     12.125,    0.45, 7242.89, 597.35,     48.500,    0.13,49712.55,1025.00,    24.250,    0.27,11940.82, 492.40
           56,     28.250,    0.26,14336.25, 507.48,     14.125,    0.52, 7314.59, 517.85,     56.500,    0.15,51249.61, 907.07,    28.250,    0.31,12111.73, 428.73
           64,     32.250,    0.30,14399.22, 446.49,     16.125,    0.59, 7351.83, 455.93,     64.500,    0.17,52297.04, 810.81,    32.250,    0.35,12261.27, 380.19
           80,     40.250,    0.37,14530.96, 361.02,     20.125,    0.73, 7389.83, 367.20,     80.500,    0.20,53644.98, 666.40,    40.250,    0.43,12466.45, 309.73
           96,     48.250,    0.44,14638.35, 303.39,     24.125,    0.87, 7415.45, 307.38,     96.500,    0.24,54460.49, 564.36,    48.250,    0.51,12583.96, 260.81
          128,     64.250,    0.59,14713.04, 229.00,     32.125,    1.16, 7447.60, 231.83,    128.500,    0.31,55466.51, 431.65,    64.250,    0.68,12753.62, 198.50
          192,     96.250,    0.87,14838.70, 154.17,     48.125,    1.73, 7488.16, 155.60,    192.500,    0.45,56979.78, 296.00,    96.250,    1.00,12933.36, 134.37
          256,    128.250,    1.17,14731.06, 114.86,     64.125,    2.31, 7460.22, 116.34,    256.500,    0.65,53296.29, 207.78,   128.250,    1.32,13027.21, 101.58

**Comment by ekondis** [comment]
Is it possible to write a log of the GPU clocks while executing the benchmark? You could use _nvidia-smi_ for this.
I'd like to make sure the clocks rates reach the advertised peak.

**Comment by mdkeehan** [comment]
I seem to be having this problem while attempting to benchmark an A100. Roughly half the expected performance.
Could you supply the suggested command line for ```nvidia-smi``` to write the log of the clocks rates and I will try to obtain the data.

**Comment by colleeneb** [comment]
I see the same -- Roughly half the expected performance. Other flop benchmarks reach the expected performance.

**Comment by ekondis** [comment]
Could you try again using the branch cuda-multiple-runs @colleeneb ?
And then try increasing the iteration count here: https://github.com/ekondis/mixbench/blob/33ef87d912fc4850eb76d386d7e45f2685ca4f75/mixbench-cuda/mix_kernels_cuda.cu#L117
