### ISSUE TITLE
mixbench-opencl is missing version_info.h

### ISSUE THREAD

**Issue by oonkjbr** [ekondis/mixbench#19]
The version_info.h file is missing from the mixbench-opencl directory. After manually copying it from mixbench-cuda to mixbench-opencl the make completed. This could be solved by including this file in the opencl directory.

**Comment by ekondis** [comment]
Oups! I missed this. Thanks for noticing!
It should be fixed now I guess with this simple [fix](https://github.com/ekondis/mixbench/commit/46dff52db05618b30a4c783251f8b1d34c937ef5)
