### ISSUE TITLE
Support on Intel GPU

### ISSUE THREAD

**Issue by nfkok** [ekondis/mixbench#22]
I tried to run mixbench-opencl on my machine with Ubuntu 18.04 and Intel Gen 9 HD Graphics.

I can build the program successfully, but when I run, i get the following error message:

`OpenCL error in file '/home/cfl-ubuntu18/mixbench/mixbench-opencl/loclutil.h' in line 48 : Code -1.`

I can see my device when i run ./mixbench-opencl -h :
```
cfl-ubuntu18@cflubuntu18:~/mixbench/build$ ./mixbench-ocl-alt -h
mixbench-ocl/alternating (v0.03-8-gbab3fb7)
Usage: mixbench-ocl [options] [device index [workgroup size [array size(1024^2)]]]

Options:
  -h or --help              Show this message
  -H or --host-alloc        Use host allocated buffer (CL_MEM_ALLOC_HOST_PTR)
  -w or --workgroup-stride  Workitem strides equal to the width of a workgroup length (default: NDRange length)
  -t or --use-os-timer      Use standard OS timer instead of OpenCL profiling timer

Available OpenCL devices:
  1. Intel(R) Gen9 HD Graphics NEO/Intel(R) OpenCL HD Graphics
```

So I would like to ask if I missed out any steps when building and does this program supports Intel GPUs.

Thanks

**Comment by ekondis** [comment]
Intel GPUs are supported. I'm actually using one myself (NEO driver as well).

It's strange that in the 1st case you got that error in line 48 since the same code path is also used for the 2nd case, where the devices are just enumerated.
Have you tried with _mixbench-ocl-ro_, as well? Same behavior?
