### ISSUE TITLE
get lower flops on when benchmarking with Tesla T4

### ISSUE THREAD

**Issue by hrshtsharma17** [ekondis/mixbench#24]
I am getting the near theoretical values for single precision and double precision but I am not getting nearby values for mix precision operation (fp16) and integer ops. I think the int ops in the benchmarking program is using int of size 4 bytes. I want to test the GPU for int4 and int8 precisions as is mentioned [here](https://www.nvidia.com/en-us/data-center/tesla-t4/) in the specifications.

I would like to know whether the mad based benchmarking should output the numbers given on the website? If yes, then why is the code showing different flops for mixed-precision (I got about 12 Gflops whereas theoretical is 65 Gflops), and for int I got 7.1 TOPs while theoretical is 130 Tops (int8)

**Comment by ekondis** [comment]
For the integer benchmarks the regular int with 32bits is used. Special datatypes as int4 or int8 would require significant code modifications.

**Comment by FabianSchuetze** [comment]
Thanks for this wonderful repo. 

Do you think it would be worth adding int8 tests, @ekondis? For Ampere these tests might be of particular interest.

**Comment by ekondis** [comment]
Thank you @FabianSchuetze.
The problem with int8 is that they are not widely available. They are supported on recent NVidia architectures via tensor cores but I think they are quite special. Perhaps, fp16 through tensor cores would make more sense as a start.
