### ISSUE TITLE
Error when running on Tesla K80

### ISSUE THREAD

**Issue by popsi** [ekondis/mixbench#25]
[Edit] Sorry for the bold text. The site makes a part of text bold but I did not do any formatting and I don't know how to fix this.

Running the benchmark on my RTX 3060Ti is OK, although the machine is nearly useless when mixbench runs (mouse pointer almost does not respond).

However, the following error is reported when I try to run mixbench on Tesla K80:
CUDA_VISIBLE_DEVICES=2 mixbench-cuda-ro

------------------------ Device specifications ------------------------
Device:              Tesla K80
CUDA driver version: 11.20
GPU clock rate:      823 MHz
Memory clock rate:   1252 MHz
Memory bus width:    384 bits
WarpSize:            32
L2 cache size:       1536 KB
Total global mem:    12206 MB
ECC enabled:         No
Compute Capability:  3.7
Total SPs:           2496 (13 MPs x 192 SPs/MP)
Compute throughput:  4110.91 GFlops (theoretical single precision FMAs)
Memory bandwidth:    240.48 GB/sec
-----------------------------------------------------------------------
Total GPU memory 12799574016, free 12733579264
Buffer size:          256MB
Trade-off type:       compute with global memory (block strided)
Elements per thread:  8
Thread fusion degree: 4
Warning:              Half precision computations are not supported
----------------------------------------------------------------------------- CSV data -----------------------------------------------------------------------------
Experiment ID, Single Precision ops,,,,              Double precision ops,,,,              Half precision ops,,,,                Integer operations,,, 
Compute iters, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Iops/byte, ex.time,   GIOPS, GB/sec
Cuda error in file '/home/popsi/Downloads/mixbench/mixbench-master/mixbench-cuda/mix_kernels_cuda_ro.cu' in line 99 : no kernel image is available for execution on the device.

Is it because half precision is not supported on the GPU? Is there some command line option or a compile option to make mixbench run on K80?

**Comment by ekondis** [comment]
AFAIK, K80 is of compute capability 3.7. So, try changing the following line:

`string(APPEND CMAKE_CUDA_FLAGS " -gencode arch=compute_52,code=[sm_52,compute_52] -gencode arch=compute_61,code=compute_61")`

at https://github.com/ekondis/mixbench/blob/master/mixbench-cuda/CMakeLists.txt#L10 to

`string(APPEND CMAKE_CUDA_FLAGS " -gencode arch=compute_37,code=[sm_37,compute_37]")
`
