### ISSUE TITLE
impossible results on Apple M1

### ISSUE THREAD

**Issue by ghost** [ekondis/mixbench#29]
Hello,

I am currently benchmarking the Apple M1 SoC for my bachelor thesis.
For the GPU I found this fancy tool, but the results are totally off.

First though, while compiling, it gave me an error that #include <CL/opencl.h> is an unknown term, and I had to manually change it to <OpenCL/opencl.h>, the "if _APPLE_" part weirdly did not work.

Now though, to the main problem. after executing the mixbench-ocl (both alt and ro, no matter if using -t or not) I get results showing things like 107 TeraFLOPs/s (107000 GFLOPS), memory bandwidth of over 4000 GB/s and equally high GIOPS.
Also, it says me that half precision and double precision are not supported, which is weird.

If using clpeak, it gives me results, not correct ones either (~1,2 TFLOPs/s) but thats closer to the real thing than >100

Do you maybe know what could cause this?

Below the results of clpeak and mixbench-ocl

With kind regards
![clpeak](https://user-images.githubusercontent.com/86931741/124399619-d4909500-dd1c-11eb-9e39-f144c9048779.png)

![mb](https://user-images.githubusercontent.com/86931741/124399623-d9eddf80-dd1c-11eb-9b8a-43030a00db03.png)

**Comment by ekondis** [comment]
Could you try again by passing the `-t` argument? Let's first make sure that the timings are applied correctly.

Regarding the header file path, I didn't have any previous experience. Can you try if the `TARGET_OS_MAC` macro definition works for you?

**Comment by ghost** [comment]
Sure, Ill append the two results, sadly no difference there, albeit -ro and -alt differ massively

And I just wrote a tiny test file, yes, the macro definition works flawlessly there.

![Bildschirmfoto 2021-07-06 um 11 01 06](https://user-images.githubusercontent.com/86931741/124575499-becdbd80-de4b-11eb-8a77-f22868737d8f.png)

![Bildschirmfoto 2021-07-06 um 11 01 45](https://user-images.githubusercontent.com/86931741/124575538-c68d6200-de4b-11eb-876e-e5159256f1e7.png)

**Comment by ekondis** [comment]
I would expect the -ro to be OK.

One more question, as it is not clear to me. Are you running it on the CPU or GPU device of M1?

**Comment by ghost** [comment]
Yeah, its not as off as the alt with its 107 TFLOPs, but the 35 TFLOPS are still way more than the 2,6 TF it should be. With none dedicated VRAM, the memory speed cant be 1000 GBps either. it should max out at around 300GBps (thats the M1 CPUs L1 Cache speed)

Thats on the GPU, as I found out, the CPU cant be used under OpenCL on the M1

**Comment by HirataYurina** [comment]
i think it caused by mixkernel.cl.
The computing method in mixkernel.cl is different from cl-peak, maybe the compiler is doing some optimization when 
doing computation in mixkernel.cl. But, it does not do optimization when  doing computation in cl-peak.
