### ISSUE TITLE
Hello, bro. why there are a valley in T4 mixben-ocl-ro?

### ISSUE THREAD

**Issue by HirataYurina** [ekondis/mixbench#30]
I use mixbench-ocl-ro to do t4 benchmark.
But i found there are a valley in T4 benchmark.
If the compute time is increasing with computation operations increasing, why there are a hollow in mem bandwidth curve?

And the data is as bellow:
single precision ops,,,,
ex.time
0.50
0.50
0.50
0.50
0.50
0.50
0.50
0.50
0.51
0.51
0.51
0.51
0.51
0.51
0.52
0.52
0.52
0.53
0.57
0.60
0.63
0.72
        
0.51
0.52
0.53
0.57
0.64

0.77
0.92
1.20
1.63
2.16

why the exe time is decreasing after 0.72?
If the compute time is increasing with computation operations increasing, 
why there are a hollow in exe time and mem bandwidth curve?

**Comment by HirataYurina** [comment]
And if we consider hiding read latency, is the exe time computing as max(computing_time, reading_time)?

**Comment by ekondis** [comment]
This can happen occasionally. In that case the reason might be that each different config corresponds to the kernel compiled as a separate binary instance. Thus, compiler can take different decisions for each during optimizing (and perhaps wrong in some cases).

I haven't observed this though on a RTX2070, which is of the same architecture.

What CUDA version are you using? Do you see this happen only for single precision computations?

One suggestion for experimentation. Try commenting out the `#pragma unroll` declarations and see what is the impact.

Hiding latency is something that is observed through this tool as for moderate increments of the "Flops/byte" ratio the memory bandwidth impact is small.

**Comment by HirataYurina** [comment]
Thanks！
