### ISSUE TITLE
VERY poor FP64 performance on Intel iGPU; likely due to lack of FP64 cores in Hardware?

### ISSUE THREAD

**Issue by tedliosu** [ekondis/mixbench#32]
According to [cpu-monkey](https://www.cpu-monkey.com/en/igpu-intel_uhd_graphics_11th_gen_16_eu-255) the integrated iGPU in the Laptop that I own (which has a i5-11400H) should get around "93 GFLOPS" max for FP64 computations at 1.45 GHz, so when I ran mixbench on the iGPU at first I got "inf" GFLOPS for all FP64 computations which was a bit strange, but then I remembered that Intel [removed FP64 cores for some of their latest gen GPUs](https://www.tomshardware.com/news/intel-arc-will-not-support-fp64-hardware), and suspecting my iGPU to be one of them, I followed [these instructions](https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md#feature-double-precision-emulation-fp64) to enable FP64 support through software emulation; after doing so I ran mixbench again and got a measly 2.6 GFLOPS of FP64 performance as you can see below, which is nowhere _close_
to the performance that cpu-monkey said I should expect. ![mixbench-sycl_fp32_vs_fp64_intel-igpu](https://user-images.githubusercontent.com/25697946/196551041-0328838b-e8ca-4268-bdda-5012783857b7.png)

May I know if the abysmal FP64 performance I observed is indeed very likely due to a lack of FP64 hardware cores in my iGPU, or is it just that my software/Operating System/GPU drivers are set-up incorrectly on my laptop?

Thank you for your assistance on this matter in advance.

**Comment by ekondis** [comment]
AFAIK, the iGPU of 11th gen CPUs do not support double precision compute. You could try also with the OpenCL version and see whether it reports FP64 supported or not.

**Comment by tedliosu** [comment]
> AFAIK, the iGPU of 11th gen CPUs do not support double precision compute. You could try also with the OpenCL version and see whether it reports FP64 supported or not.

@ekondis As you can see below, the benchmark says `Warning:                Double precision computations are not supported` IF I don't run `export OverrideDefaultFP64Settings=1` followed by `export IGC_EnableDPEmulation=1` beforehand...
![no_fp64_emulation_mixbench_opencl](https://user-images.githubusercontent.com/25697946/197333751-ba6cd6aa-c83c-4c76-9498-bf8c9dc56dc3.png)
... and when I do run the two aforementioned export commands BEFORE I run your benchmark, I still get the same abysmal fp64 performance as I did with the sycl versions of this benchmark:
![fp64_emulation_enabled_mixbench_opencl](https://user-images.githubusercontent.com/25697946/197333848-f285f371-f429-4c8c-a61a-70109ba922da.png)
So does this mean that my Operating System and my graphics drivers are all configured correctly, and the _only_ reason as to why I'm getting these abysmal fp64 results is that the Intel iGPU in my system does _not_ have **hardware FP64 cores built into it**?

I just want to triple check to make sure that is the case so that when I go ahead and contact sites like cpu-monkey and suggest to them to change their FP64 compute data about 11th+ Gen Intel GPUs, that I don't get hit with a response along the lines of: "but are you sure that's not simply a 'software or hardware anomaly' issue you're having?"

**Comment by ekondis** [comment]
I believe that the GPU does indeed not support FP64. The performance you see is expected since you are based on emulation.

ref: https://community.intel.com/t5/GPU-Compute-Software/Iris-Xe-Graphics-can-t-compute-double-precision-floating-point/m-p/1284101/highlight/true#M133

**Comment by tedliosu** [comment]
> I believe that the GPU does indeed not support FP64. The performance you see is expected since you are based on emulation.
> 
> ref: https://community.intel.com/t5/GPU-Compute-Software/Iris-Xe-Graphics-can-t-compute-double-precision-floating-point/m-p/1284101/highlight/true#M133

@ekondis Thank you so much for your confirmation on the matter; I am closing this issue as I've now got the answers I needed.
