### ISSUE TITLE
mixbench-cuda : erroneous A100 Total SPs count

### ISSUE THREAD

**Issue by ChristopheHubert72** [ekondis/mixbench#47]
I'm not 100% sure, but I think that one information (at least) displayed for A100 is wrong.
 This is the output for mixbench-cuda :
Device:              NVIDIA A100 80GB PCIe
CUDA driver version: 12.30
GPU clock rate:      1410 MHz
Memory clock rate:   756 MHz
Memory bus width:    5120 bits
WarpSize:            32
L2 cache size:       40960 KB
Total global mem:    81049 MB
ECC enabled:         Yes
Compute Capability:  8.0
Total SPs:           13824 (108 MPs x 128 SPs/MP)
Compute throughput:  38983.68 GFlops (theoretical single precision FMAs)
Memory bandwidth:    1935.36 GB/sec

Total SPs should be half that (the A100 as 108 MP but only 64 SP). It impacts the theorical Compute throughput.

Made this small patch

--- lcutil.h.old	2023-11-30 10:32:24.795092298 +0000
+++ lcutil.h	2023-11-30 10:26:29.237948462 +0000
@@ -35,6 +35,7 @@
 			default: return 128;
 		}
 		case 7:  return 64;
+		case 8:  return 64;
 		default: return 128;
 	}
 }

New output:
Device:              NVIDIA A100 80GB PCIe
CUDA driver version: 12.30
GPU clock rate:      1410 MHz
Memory clock rate:   756 MHz
Memory bus width:    5120 bits
WarpSize:            32
L2 cache size:       40960 KB
Total global mem:    81049 MB
ECC enabled:         Yes
Compute Capability:  8.0
Total SPs:           6912 (108 MPs x 64 SPs/MP)
Compute throughput:  19491.84 GFlops (theoretical single precision FMAs)
Memory bandwidth:    1935.36 GB/sec

**Comment by ekondis** [comment]
https://github.com/ekondis/mixbench/pull/52 should be okay I guess
