### ISSUE TITLE
OpenCL error in file 'mix_kernels_ocl.cpp' in line 179 : Code -14.

### ISSUE THREAD

**Issue by Bidski** [ekondis/mixbench#8]
Running the alternating OpenCL kernel on my Intel NUC7i7BNH produces the following output

```
mixbench-ocl/alternating (v0.02-49-g91ba989)
Use "-h" argument to see available options
------------------------ Device specifications ------------------------
Platform:            Intel(R) OpenCL
Device:              Intel(R) HD Graphics/Intel(R) Corporation
Driver version:      r4.1.61547
Address bits:        64
GPU clock rate:      1150 MHz
Total global mem:    6290 MB
Max allowed buffer:  3145 MB
OpenCL version:      OpenCL 2.0 
Total CUs:           47
-----------------------------------------------------------------------
Buffer size:            64MB
Workgroup size:         256
Workitem stride:        NDRange
Buffer allocation:      Device allocated
Timer:                  CL event based
Loading kernel source file...
Precompilation of kernels... [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]
----------------------------------------------------------------------------- CSV data -----------------------------------------------------------------------------
Experiment ID, Single Precision ops,,,,              Double precision ops,,,,              Half precision ops,,,,                Integer operations,,, 
Compute iters, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Flops/byte, ex.time,  GFLOPS, GB/sec, Iops/byte, ex.time,   GIOPS, GB/sec
OpenCL error in file 'mix_kernels_ocl.cpp' in line 179 : Code -14.
```

Available devices, as reported by `mixbench-ocl-alt -h`.
```
Available OpenCL devices:
  1. Intel(R) HD Graphics         (intel driver)
  2. Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  3. Intel(R) HD Graphics Kabylake ULT GT3    (beignet driver)

```

Readonly kernel runs without error. Both kernels run fine if I use the beignet platform/device or the CPU.

Outputs from the other devices
[ALT CPU](https://github.com/ekondis/mixbench/files/1512687/mixbench-ocl-alt_cpu.log)
[RO CPU](https://github.com/ekondis/mixbench/files/1512690/mixbench-ocl-ro_cpu.log)
[ALT Beignet GPU](https://github.com/ekondis/mixbench/files/1512691/mixbench-ocl-alt_gpu.log)
[RO Beignet GPU](https://github.com/ekondis/mixbench/files/1512692/mixbench-ocl-ro_gpu.log)
[RO Intel GPU](https://github.com/ekondis/mixbench/files/1512697/mixbench-ocl-ro_gpu_intel.log)

**Comment by ekondis** [comment]
It seems as the half precision compute kernel execution failed for some reason. I would try running the benchmark with a smaller workgroup size, e.g. 128 or 64. You can change the default through a command line argument.

**Comment by Bidski** [comment]
I just tried running alternating kernel with all combinations of the following settings
Workgroup size: 256, 128, 64, 32, 16
Buffer size (MB): 64, 32, 16

All of them resulted in the same error.

**Comment by ekondis** [comment]
Perhaps kernel is not compiled correctly with the propriatery intel driver. However, it's difficult to validate this assumption.

**Comment by ekondis** [comment]
Since NEO driver is the most up to date for Intel GPUs, this issue is being closed.
